# Generated by Django 6.0 on 2025-12-19 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='موضوع')),
                ('summary', models.TextField(verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(verbose_name='شناسه')),
                ('thumbnail', models.ImageField(unique=True, upload_to='', verbose_name='تصویر بندانگشتی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_verify', models.BooleanField(default=True, verbose_name='مورد تائید')),
                ('is_pin', models.BooleanField(default=False, verbose_name='ویژه')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110, verbose_name='نام وبلاگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات وبلاگ')),
                ('anonymons_bloger', models.BooleanField(default=False, help_text='اگر فعال شود نام نویسنده در بلاگ نمایش داده نمی شود', verbose_name='ناشناس کردن نویسنده')),
                ('bloger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
