# Generated by Django 6.0 on 2025-12-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': 'وبلاگ', 'verbose_name_plural': 'وبلاگ ها'},
        ),
    ]
