# Generated by Django 6.0 on 2025-12-19 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_options_alter_blog_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='anonymons_bloger',
            new_name='anonymos_bloger',
        ),
    ]
